---
- name: Create phone provisioning configs
  ansible.builtin.template:
    src: "{{ item.type }}.j2"
    dest: "/srv/tftp/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
    vars:
      model: {{ item }}
  with_items: {{ phone_models }}
