---
- name: Allow port 69 (nice) for TFTP
  community.general.ufw:
    rule: allow
    proto: udp
    port: "69"

- name: Allow port 67 for DHCP
  community.general.ufw:
    rule: allow
    proto: udp
    port: "67"

- name: Allow port 80 for HTTP proxy
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "80"

- name: Reload UFW
  community.general.ufw:
    state: reloaded
