---

- name: Restart dhcpd
  ansible.builtin.service:
    name: isc-dhcp-server
    state: "{{ 'restarted' if branch == 'prod' else 'stopped' }}"
    enabled: "{{ 'yes' if branch == 'prod' else 'no' }}"
