---
- include: locale.yaml

- include: packages.yaml

- include: network.yaml

- include: user.yaml

- include: timesyncd.yaml
# - name: Show facts available on the system
#   ansible.builtin.debug:
#     var: ansible_facts
