---
- include: locale.yaml
  tags:
    - locale

- include: packages.yaml
  tags:
    - packages

- include: network.yaml
  tags:
    - network

- include: user.yaml
  tags:
    - user

- include: rsyslog.yaml
  tags:
    - rsyslog-clients

- include: firewall_rules.yaml
  tags:
    - firewall

- include: packages.yaml

- include: network.yaml

- include: "etc_hosts.yaml"

- include: mail.yaml
  when: "'smtp' not in group_names"

- include: user.yaml

- include: timesyncd.yaml

- include: freeipa_enroll.yaml
# - name: Show facts available on the system
#   ansible.builtin.debug:
#     var: ansible_facts
