---
- include: locale.yaml
  tags:
    - locale

- include: packages.yaml
  tags:
    - packages

- include: network.yaml
  tags:
    - network

- include: user.yaml
  tags:
    - user

- include: firewall_rules.yaml
  tags:
    - firewall

- include: packages.yaml

- include: network.yaml

- include: user.yaml

- include: timesyncd.yaml
# - name: Show facts available on the system
#   ansible.builtin.debug:
#     var: ansible_facts
