---
- name: Disable Firefox autofill
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "syspref.js", dest: "/etc/firefox/syspref.js" }

- name: WiFi credentials
  ansible.builtin.template:
    src: NMConnection.j2
    dest: "/etc/NetworkManager/system-connections/{{ item.ssid }}.nmconnection"
    owner: root
    group: root
    mode: 0600
  with_items: "{{ wifi_creds }}"
