---
- name: Disable Firefox autofill
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: "syspref.js", dest: "/etc/firefox/syspref.js" }
