---
- name: Create break glass account
  ansible.builtin.user:
    name: "{{ break_glass_user }}"
    password: "{{ break_glass_pass }}"
    shell: /bin/bash

- name: Set authorized key, removing all the authorized keys already set
  ansible.posix.authorized_key:
    user: "{{ break_glass_user }}"
    key: "{{ lookup('file', 'public_keys/keys.pub') }}"
    state: present
    exclusive: true

- name: Give user sudo access
  lineinfile:
    path: /etc/sudoers
    line: "{{ break_glass_user }} ALL=(ALL) NOPASSWD: ALL"
