---
- name: Install SMTP server package
  ansible.builtin.apt:
    name: "{{ packages.smtp }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true

- name: Install Postfix config
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: "0640"
    owner: root
    group: postfix
  notify:
    - Restart Postfix

- name: Install Postfix password file
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: "0640"
    owner: root
    group: postfix
  notify:
    - Restart Postfix

- name: Activate Postfix password map
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd
  notify:
    - Restart Postfix
