---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    # dhcp:
    #   hosts:
    #     dhcp1:
    #     dhcp2:
    # dns:
    #   hosts:
    #     dns1:
    #     dns2:
    # rsyslog:
    #   hosts:
    #     rsyslog-1:
    ubuntu-lxc:
      hosts:
        ubuntu-lxc:
    ubuntu-vm:
      hosts:
        ubuntu-vm:
