    - name: Install packages
      package:
        name:
          - fortune
          - update-motd
        state: latest

    - name: "Remove MOTD news"
      become: True
      file:
        path: "{{item}}"
        state: absent
      loop:
        - /etc/update-motd.d/10-help-text
        - /etc/update-motd.d/50-motd-news
        - /etc/update-motd.d/91-contract-ua-esm-status
        - /etc/update-motd.d/91-release-upgrade
        - /etc/update-motd.d/98-esm-announce

    - name: "Set /etc/update-motd.d/91-fortune"
      become: True
      shell: printf '#!/bin/sh\n\n/usr/games/fortune' > /etc/update-motd.d/91-motd

    - name: "chmod 0755 /etc/update-motd.d/91-fortune"
      become: True
      file: path=/etc/update-motd.d/91-motd owner=root group=root mode='0755'

    - name: "update-motd"
      become: True
      shell: update-motd

