---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog

- name: Restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
