---
- name: Install TFTP packages
  ansible.builtin.apt:
    name: "{{ packages.tftp }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true

- name: Create tftp directory
  ansible.builtin.file:
    path: /srv/tftp
    state: directory