---
- name: Allow port 53 UDP for DNS
  community.general.ufw:
    rule: allow
    proto: udp
    port: "53"

- name: Allow port 53 TCP for DNS
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "53"

- name: Reload UFW
  community.general.ufw:
    state: reloaded
