---
- name: Install named package
  ansible.builtin.apt:
    name: "{{ packages.named }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  notify:
  - Restart named

- name: Install named config
  ansible.builtin.copy:
    src: "named.conf"
    dest: "/etc/bind/named.conf"
    mode: 0660
    owner: root
    group: bind
  notify:
  - Restart named

- name: Generate magevent.net zone file
  ansible.builtin.template:
    src: magevent.net.zone.j2
    dest: /var/lib/bind/magevent.net.zone
    mode: 0660
    owner: root
    group: bind
  notify:
  - Restart named

- name: Install additional zone files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/bind/{{ item }}"
    mode: 0660
    owner: root
    group: bind
  with_items:
  - "onsite.reggie.magfest.org.zone"
  - "onsite.uber.magfest.org.zone"
  - "win.magevent.net.zone"
  notify:
  - Restart named
