---
- name: Initial Ubuntu setup
  hosts:
  - all
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
  - ubuntu
  - dns

- name: CUPS setup
  hosts:
    - cups
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - cups

- name: rsyslog setup
  hosts:
  - rsyslog
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
  - rsyslog