---
- name: Initial Ubuntu setup
  hosts:
  - all
  remote_user: root
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
  - ubuntu
  - dns

- name: CUPS setup
  hosts:
  - cups
  remote_user: root
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
  - cups

- name: rsyslog setup
  hosts:
  - rsyslog
  remote_user: root
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
  - rsyslog
