---
name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: terraform-linters/setup-tflint@v1
    - name: Install Proxmox provider
      working-directory: ./terraform
      run: bash ./terraform-proxmox-plugin.sh
    - uses: pre-commit/action@v2.0.3
