---
name: Terraform - Lint

on:
  push:
    paths:
      - "terraform/*"
      - ".github/workflows/terraform-lint.yaml"
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main
    - name: Run tfsec with reviewdog output on the PR
      uses: reviewdog/action-tfsec@master
      with:
        github_token: ${{ secrets.github_token }}
        level: info # Get more output from reviewdog
        reporter: github-pr-review # Change reviewdog reporter
        filter_mode: nofilter # Check all files, not just the diff
        fail_on_error: true # Fail action if errors are found
        flags: -tee # Add debug flag to reviewdog
        tfsec_flags: "" # Optional
