---
name: Terraform - Lint

on:
  push:
    paths:
      - "terraform/*"
      - ".github/workflows/terraform-lint.yaml"
  pull_request:
    paths:
      - "terraform/*"
      - ".github/workflows/terraform-lint.yaml"


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint

      - name: Install Proxmox provider
        run: bash ./terraform-proxmox-plugin.sh

      - name: Run `terraform fmt`
        run: terraform fmt -diff -no-color -recursive

      - name: Run `terraform init`
        run: terraform init -backend=false

      - name: Run `terraform validate`
        run: terraform validate -no-color
