---
name: Terraform - Lint

on:
  push:
    paths:
      - "terraform/*"
      - ".github/workflows/terraform-lint.yaml"
  pull_request:


jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.12.29"

      - name: Run `terraform fmt`
        run: terraform fmt -diff -check -no-color -recursive

      - name: Run `terraform init`
        run: terraform init

      - name: Run `terraform validate`
        run: terraform validate -no-color
